"""initial schema

Revision ID: 28fe52cb8267
Revises: 
Create Date: 2026-08-16 21:43:16.169304
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '28fe52cb8267'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('geometry_geojson', sa.JSON(), nullable=False),
    sa.Column('geom', sa.JSON(), nullable=True),
    sa.Column('bbox_west', sa.Float(), nullable=False),
    sa.Column('bbox_south', sa.Float(), nullable=False),
    sa.Column('bbox_east', sa.Float(), nullable=False),
    sa.Column('bbox_north', sa.Float(), nullable=False),
    sa.Column('area_km2', sa.Float(), nullable=False),
    sa.Column('crs', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_regions_bbox', 'regions', ['bbox_west', 'bbox_south', 'bbox_east', 'bbox_north'], unique=False)
    op.create_table('analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('region_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('status_detail', sa.String(length=400), nullable=True),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('period_a_start', sa.Date(), nullable=False),
    sa.Column('period_a_end', sa.Date(), nullable=False),
    sa.Column('period_b_start', sa.Date(), nullable=True),
    sa.Column('period_b_end', sa.Date(), nullable=True),
    sa.Column('max_cloud_cover', sa.Float(), nullable=False),
    sa.Column('include_land_cover', sa.Boolean(), nullable=False),
    sa.Column('include_interpretation', sa.Boolean(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('methodology', sa.JSON(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('layer_manifest', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_created_at'), 'analyses', ['created_at'], unique=False)
    op.create_index(op.f('ix_analyses_region_id'), 'analyses', ['region_id'], unique=False)
    op.create_index(op.f('ix_analyses_status'), 'analyses', ['status'], unique=False)
    op.create_table('environmental_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('period', sa.String(length=1), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('provenance', sa.String(length=24), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_environmental_metrics_analysis_id'), 'environmental_metrics', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_environmental_metrics_key'), 'environmental_metrics', ['key'], unique=False)
    op.create_index('ix_metric_analysis_key', 'environmental_metrics', ['analysis_id', 'key'], unique=False)
    op.create_table('model_predictions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('model_name', sa.String(length=120), nullable=False),
    sa.Column('model_version', sa.String(length=40), nullable=False),
    sa.Column('model_backend', sa.String(length=60), nullable=False),
    sa.Column('task', sa.String(length=60), nullable=False),
    sa.Column('predicted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('class_distribution', sa.JSON(), nullable=False),
    sa.Column('mean_confidence', sa.Float(), nullable=True),
    sa.Column('low_confidence_fraction', sa.Float(), nullable=True),
    sa.Column('evaluation_metrics', sa.JSON(), nullable=True),
    sa.Column('input_metadata', sa.JSON(), nullable=True),
    sa.Column('preprocessing_version', sa.String(length=40), nullable=True),
    sa.Column('prediction_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_predictions_analysis_id'), 'model_predictions', ['analysis_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=False),
    sa.Column('interpretation', sa.JSON(), nullable=True),
    sa.Column('visual_interpretation', sa.JSON(), nullable=True),
    sa.Column('interpretation_provider', sa.String(length=120), nullable=True),
    sa.Column('interpretation_model', sa.String(length=120), nullable=True),
    sa.Column('html_path', sa.String(length=500), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_analysis_id'), 'reports', ['analysis_id'], unique=False)
    op.create_table('satellite_observations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('period', sa.String(length=1), nullable=False),
    sa.Column('source_id', sa.String(length=200), nullable=False),
    sa.Column('provider', sa.String(length=200), nullable=False),
    sa.Column('dataset', sa.String(length=120), nullable=False),
    sa.Column('observation_date', sa.Date(), nullable=False),
    sa.Column('acquisition_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cloud_cover_percent', sa.Float(), nullable=True),
    sa.Column('processing_level', sa.String(length=32), nullable=True),
    sa.Column('platform', sa.String(length=64), nullable=True),
    sa.Column('instrument', sa.String(length=64), nullable=True),
    sa.Column('crs', sa.String(length=32), nullable=True),
    sa.Column('resolution_m', sa.Float(), nullable=True),
    sa.Column('license', sa.String(length=200), nullable=True),
    sa.Column('bands_used', sa.JSON(), nullable=False),
    sa.Column('footprint_geojson', sa.JSON(), nullable=True),
    sa.Column('geom', sa.JSON(), nullable=True),
    sa.Column('scene_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_satellite_observations_analysis_id'), 'satellite_observations', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_satellite_observations_source_id'), 'satellite_observations', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_satellite_observations_source_id'), table_name='satellite_observations')
    op.drop_index(op.f('ix_satellite_observations_analysis_id'), table_name='satellite_observations')
    op.drop_table('satellite_observations')
    op.drop_index(op.f('ix_reports_analysis_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_model_predictions_analysis_id'), table_name='model_predictions')
    op.drop_table('model_predictions')
    op.drop_index('ix_metric_analysis_key', table_name='environmental_metrics')
    op.drop_index(op.f('ix_environmental_metrics_key'), table_name='environmental_metrics')
    op.drop_index(op.f('ix_environmental_metrics_analysis_id'), table_name='environmental_metrics')
    op.drop_table('environmental_metrics')
    op.drop_index(op.f('ix_analyses_status'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_region_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_created_at'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_index('ix_regions_bbox', table_name='regions')
    op.drop_table('regions')
    # ### end Alembic commands ###
