"""NatureVision API application."""

from __future__ import annotations

import time
import uuid
from contextlib import asynccontextmanager

from fastapi import APIRouter, FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware

from app.api.deps import shutdown_clients
from app.api.routes import analysis, imagery, processing, reports, system
from app.core.config import settings
from app.core.errors import register_exception_handlers
from app.core.logging import configure_logging, get_logger, request_id_var
from app.db.session import dispose_engine, init_database

logger = get_logger(__name__)

DESCRIPTION = """\
Geospatial environmental intelligence over Sentinel-2 Level-2A imagery.

Measured values are produced by deterministic raster processing. Land-cover
values are predictions from a trained classifier and are labelled as such.
Interpretation text is generated by a language model strictly from the measured
evidence and is validated against it before being returned.
"""


@asynccontextmanager
async def lifespan(_app: FastAPI):
    configure_logging()
    settings.ensure_directories()
    try:
        await init_database()
    except Exception as exc:
        # A database outage must surface on /health rather than preventing the
        # process from starting, so an operator can see why it is degraded.
        logger.error("database_initialisation_failed", error=str(exc)[:300])
    logger.info(
        "application_started",
        environment=settings.app_env,
        imagery_collection=settings.stac_collection,
        interpretation_configured=settings.language_enabled,
    )
    yield
    await shutdown_clients()
    await dispose_engine()
    logger.info("application_stopped")


def create_app() -> FastAPI:
    app = FastAPI(
        title=f"{settings.app_name} API",
        description=DESCRIPTION,
        version="0.1.0",
        lifespan=lifespan,
        docs_url="/docs",
        redoc_url="/redoc",
        openapi_url="/openapi.json",
    )

    app.add_middleware(
        CORSMiddleware,
        allow_origins=settings.cors_origins,
        allow_credentials=False,
        allow_methods=["GET", "POST", "DELETE", "OPTIONS"],
        allow_headers=["*"],
    )

    @app.middleware("http")
    async def request_context(request: Request, call_next):
        """Attach a request id and emit one structured access log per request."""
        request_id = request.headers.get("x-request-id") or uuid.uuid4().hex[:16]
        token = request_id_var.set(request_id)
        started = time.perf_counter()
        try:
            response = await call_next(request)
        finally:
            request_id_var.reset(token)
        duration_ms = round((time.perf_counter() - started) * 1000, 2)
        response.headers["x-request-id"] = request_id
        if request.url.path not in {"/health", f"{settings.api_prefix}/health"}:
            logger.info(
                "request_completed",
                method=request.method,
                path=request.url.path,
                status_code=response.status_code,
                duration_ms=duration_ms,
            )
        return response

    register_exception_handlers(app)

    api = APIRouter(prefix=settings.api_prefix)
    api.include_router(system.router)
    api.include_router(imagery.router)
    api.include_router(processing.router)
    api.include_router(analysis.router)
    api.include_router(reports.router)
    app.include_router(api)

    # Unprefixed liveness path, for container and load-balancer probes.
    app.include_router(system.router, include_in_schema=False)

    return app


app = create_app()
